import './globals.css'
import { Roboto } from 'next/font/google'
export const metadata = {
  title: 'Frontend Mentor | Newsletter sign-up form with success message',
  description: 'Generated by create next app',
}

const font = Roboto({ weight: ['400', '700'], subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
      <body className={font.className}>{children}</body>
    </html>
  )
}
